In [1]:
from IPython.core.interactiveshell import InteractiveShell

InteractiveShell.ast_node_interactivity = "all"


class display(object):
    """Display HTML representation of multiple objects"""

    template = """<div style="float: left; padding: 10px;">
    <p style='font-family:"Courier New", Courier, monospace'>{0}</p>{1}
    </div>"""

    def __init__(self, *args):
        self.args = args

    def _repr_html_(self):
        return "\n".join(
            self.template.format(a, eval(a)._repr_html_()) for a in self.args
        )

    def __repr__(self):
        return "\n\n".join(a + "\n" + repr(eval(a)) for a in self.args)

In [2]:
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6]])
a

b = a.flatten()
b
c = a.flatten("F")
c

array([[1, 2, 3],
       [4, 5, 6]])

array([1, 2, 3, 4, 5, 6])

array([1, 4, 2, 5, 3, 6])

In [6]:
from dataclasses import dataclass, field
from typing import Optional
import pandas as pd
import numpy as np
from ordered_set import OrderedSet
from tspace.config.drivers import drivers
from tspace.config.vehicles import trucks_by_id
from tspace.config.drivers import drivers_by_id

# DriverSet = OrderedSet(
#     [
#         'wang-cheng',
#         'li-changlong',
#         'chen-hongmei',
#         'zheng-longfei',
#     ]
# )
# DriverSet[0]
# DriverSet.get_loc('wang-cheng')
# DriverSet

In [7]:
import pandas as pd
import numpy as np
from datetime import datetime

ts = pd.to_datetime(datetime.now())
ts_ind = ts + pd.to_timedelta(np.arange(2), "H")
ts_ind
df = pd.DataFrame(a, index=ts_ind, columns=["c1", "c2", "c3"])
df
df.index[0]

/var/folders/sy/zg00xvpj2597p3wtxcmy_c100000gp/T/ipykernel_43444/1885882896.py:6: FutureWarning: 'H' is deprecated and will be removed in a future version. Please use 'h' instead of 'H'.
  ts_ind = ts + pd.to_timedelta(np.arange(2), "H")


DatetimeIndex(['2024-06-25 16:45:58.982114', '2024-06-25 17:45:58.982114'], dtype='datetime64[ns]', freq=None)

c1  c2  c3
2024-06-25 16:45:58.982114   1   2   3
2024-06-25 17:45:58.982114   4   5   6

Timestamp('2024-06-25 16:45:58.982114')

In [8]:
ts
ts_end = pd.to_datetime(datetime.now())
ts_end
span = ts_end - ts
span
span_each_row = span / 4
span_each_row
np.linspace(0, 4, 5)
ts_ser = ts + pd.to_timedelta(np.linspace(1, 4, 4) * span_each_row, unit="s")
ts_ser

Timestamp('2024-06-25 16:45:58.982114')

Timestamp('2024-06-25 16:45:58.993386')

Timedelta('0 days 00:00:00.011272')

Timedelta('0 days 00:00:00.002818')

array([0., 1., 2., 3., 4.])

DatetimeIndex(['2024-06-25 16:45:58.984932', '2024-06-25 16:45:58.987750',
               '2024-06-25 16:45:58.990568', '2024-06-25 16:45:58.993386'],
              dtype='datetime64[ns]', freq=None)

In [9]:
df_ts = pd.DataFrame(np.array([ts]), columns=["timestamp"])
df_ts

timestamp
0 2024-06-25 16:45:58.982114

In [10]:
s = np.arange(10)
s

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Generate state

In [11]:
ss = np.arange(12)
a1 = ss[:4].tolist()
a2 = ss[4:8].tolist()
a3 = ss[8:].tolist()
ss = [a1, a2, a3]
ss
df_s = pd.DataFrame(ss, columns=["t", "v", "p", "b"])  # .set_index('t')
df_s

[[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11]]

t  v   p   b
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11

In [12]:
np.arange(0, 4 * 20, 20)

array([ 0, 20, 40, 60])

In [13]:
ts_ind = ts + pd.to_timedelta(np.arange(0, 4 * 20, 20), "ms")
ts_ind
ss = np.arange(12)
a1 = ss[:4]
a2 = ss[4:8]
a3 = ss[8:]
df_ss = pd.DataFrame(
    {"timestep": ts_ind, "velocity": a1, "thrust": a2, "brake": a3}
)  # .set_index('timestep')
df_ss.columns.name = "tuple"
df_ss
df_ss[["velocity", "thrust", "brake"]]

DatetimeIndex(['2024-06-25 16:45:58.982114', '2024-06-25 16:45:59.002114',
               '2024-06-25 16:45:59.022114', '2024-06-25 16:45:59.042114'],
              dtype='datetime64[ns]', freq=None)

tuple                   timestep  velocity  thrust  brake
0     2024-06-25 16:45:58.982114         0       4      8
1     2024-06-25 16:45:59.002114         1       5      9
2     2024-06-25 16:45:59.022114         2       6     10
3     2024-06-25 16:45:59.042114         3       7     11

tuple  velocity  thrust  brake
0             0       4      8
1             1       5      9
2             2       6     10
3             3       7     11

In [14]:
npa_ss_flatten = df_ss[["velocity", "thrust", "brake"]].to_numpy().flatten()
npa_ss_flatten

array([ 0,  4,  8,  1,  5,  9,  2,  6, 10,  3,  7, 11])

In [15]:
ui_t = df_ss.loc[:, ["velocity", "thrust"]]
ui_t
power_t = ui_t.prod(axis=1)
power_t
power_t.sum()

tuple  velocity  thrust
0             0       4
1             1       5
2             2       6
3             3       7

0     0
1     5
2    12
3    21
dtype: int64

38

In [46]:
state = df_ss.stack().swaplevel(0, 1)
state.name = "state"
state.index.names = ["rows", "idx"]
state.sort_index(inplace=True)
state

rows      idx
brake     0                               8
          1                               9
          2                              10
          3                              11
thrust    0                               4
          1                               5
          2                               6
          3                               7
timestep  0      2024-06-25 16:45:58.982114
          1      2024-06-25 16:45:59.002114
          2      2024-06-25 16:45:59.022114
          3      2024-06-25 16:45:59.042114
velocity  0                               0
          1                               1
          2                               2
          3                               3
Name: state, dtype: object

In [47]:
type(state)
state

pandas.core.series.Series

rows      idx
brake     0                               8
          1                               9
          2                              10
          3                              11
thrust    0                               4
          1                               5
          2                               6
          3                               7
timestep  0      2024-06-25 16:45:58.982114
          1      2024-06-25 16:45:59.002114
          2      2024-06-25 16:45:59.022114
          3      2024-06-25 16:45:59.042114
velocity  0                               0
          1                               1
          2                               2
          3                               3
Name: state, dtype: object

In [48]:
state.values

array([8, 9, 10, 11, 4, 5, 6, 7, Timestamp('2024-06-25 16:45:58.982114'),
       Timestamp('2024-06-25 16:45:59.002114'),
       Timestamp('2024-06-25 16:45:59.022114'),
       Timestamp('2024-06-25 16:45:59.042114'), 0, 1, 2, 3], dtype=object)

In [18]:
# idx = pd.IndexSlice
state_stripped = state[["velocity", "thrust", "brake"]]
state_stripped
state_stripped.values

rows      idx
velocity  0       0
          1       1
          2       2
          3       3
thrust    0       4
          1       5
          2       6
          3       7
brake     0       8
          1       9
          2      10
          3      11
Name: state, dtype: object

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11], dtype=object)

In [19]:
# from functools import reduce
#
#
# velocity = pd.Series(ss[:4], name='velocity')
# thrust = pd.Series(ss[4:8], name='thrust')
# brake = pd.Series(ss[8:], name='brake')
# series = [velocity, thrust, brake]
# state = reduce(
#     lambda x, y: pd.merge(x, y, how='outer', left_index=True, right_index=True), series
# )
# state = state.stack().swaplevel(0, 1).sort_index()
# state.name = 'state'
# state
# len(state)

In [20]:
# from functools import reduce
#
#
# velocity = pd.Series(s[:4], name='velocity')
# thrust = pd.Series(s[4:7], name='thrust')
# brake = pd.Series(s[7:], name='brake')
# series = [velocity, thrust, brake]
# state = reduce(
#     lambda x, y: pd.merge(x, y, how='outer', left_index=True, right_index=True), series
# )
# state = state.stack().swaplevel(0, 1).sort_index()
# state.name = 'state'
# state
# len(state)
#
#

### generate action

In [21]:
from functools import reduce

a = len(ss) + np.arange(15)
speed_ser = pd.Series(np.linspace(40, 60, 3), name="speed")
# row_ser
row_dict = {f"r{i}": a[i * 5 : i * 5 + 5] for i in np.arange(3)}
row_dict
row_array = a.reshape(3, 5).transpose()
row_array
rows_df = pd.DataFrame(row_array)
rows_df.columns = [f"r{i}" for i in np.arange(3)]
rows_df

{'r0': array([12, 13, 14, 15, 16]),
 'r1': array([17, 18, 19, 20, 21]),
 'r2': array([22, 23, 24, 25, 26])}

array([[12, 17, 22],
       [13, 18, 23],
       [14, 19, 24],
       [15, 20, 25],
       [16, 21, 26]])

r0  r1  r2
0  12  17  22
1  13  18  23
2  14  19  24
3  15  20  25
4  16  21  26

In [22]:
ts_ind = ts + pd.to_timedelta(np.arange(5 * 20, 8 * 20, 20), "ms")
ts_ser = pd.Series(ts_ind, name="timestep")
throttle_ser = pd.Series(np.linspace(0, 1.0, 5), name="throttle")
# throttle_ser
dfs = [rows_df, ts_ser, speed_ser, throttle_ser]
action = (
    reduce(
        lambda left, right: pd.merge(
            left, right, how="outer", left_index=True, right_index=True
        ),
        dfs,
    )
    .stack()
    .swaplevel(0, 1)
    .sort_index()
)

action.name = "action"
action.index.names = ["rows", "idx"]
action.index
action
# action = pd.concat([df.DataFrame(row_dict),df.Series(row_ind),df.Series(ts_ind),df.Series(pedal_ind)],axis=1)
# action
# pedal_ind
# action_ind = pd.MultiIndex.from_product([row_ind, ts_ind], names=['row', 'timestamp'])
# a
# speed_row, row_name = *row_dict
# action = (
#     pd.DataFrame(
#         {
#             **row_dict,
#             'throttle': pedal_ind,
#             'speed': [r[1] for r in row_ind],
#         }
#     )  # .set_index('pedal')
#     # .stack()
#     # .swaplevel(0, 1)
#     .sort_index()
# )
# action
# action.columns
# action.columns = pd.MultiIndex.from_arrays(
#     [action.columns, ts_ind], names=['nominalspeed', 'timestep']
# )
# action = action.stack([0, 1]).swaplevel(0, 1).swaplevel(1, 2).sort_index()
# action.name = 'action'
# # action.index.names = ['nominalspeed', 'timestamp']
# # action.index
# action

MultiIndex([(      'r0', 0),
            (      'r0', 1),
            (      'r0', 2),
            (      'r0', 3),
            (      'r0', 4),
            (      'r1', 0),
            (      'r1', 1),
            (      'r1', 2),
            (      'r1', 3),
            (      'r1', 4),
            (      'r2', 0),
            (      'r2', 1),
            (      'r2', 2),
            (      'r2', 3),
            (      'r2', 4),
            (   'speed', 0),
            (   'speed', 1),
            (   'speed', 2),
            ('throttle', 0),
            ('throttle', 1),
            ('throttle', 2),
            ('throttle', 3),
            ('throttle', 4),
            ('timestep', 0),
            ('timestep', 1),
            ('timestep', 2)],
           names=['rows', 'idx'])

rows      idx
r0        0                              12
          1                              13
          2                              14
          3                              15
          4                              16
r1        0                              17
          1                              18
          2                              19
          3                              20
          4                              21
r2        0                              22
          1                              23
          2                              24
          3                              25
          4                              26
speed     0                            40.0
          1                            50.0
          2                            60.0
throttle  0                             0.0
          1                            0.25
          2                             0.5
          3                            0.75
          4       

In [23]:
# action = (
#     reduce(
#         lambda left, right: pd.merge(
#             left, right, how='outer', left_index=True, right_index=True
#         ),
#         dfs,
#     )
#     .stack()
#     .swaplevel(0, 1)
#     .sort_index()
# )
#
# action.name = 'action'
# action.index.names = ['rows', 'idx']
# action.index
# action
action1 = reduce(
    lambda left, right: pd.merge(
        left, right, how="outer", left_index=True, right_index=True
    ),
    dfs,
)
action1
action2 = action1.stack()
type(action2)

r0  r1  r2                   timestep  speed  throttle
0  12  17  22 2024-06-25 16:45:59.082114   40.0      0.00
1  13  18  23 2024-06-25 16:45:59.102114   50.0      0.25
2  14  19  24 2024-06-25 16:45:59.122114   60.0      0.50
3  15  20  25                        NaT    NaN      0.75
4  16  21  26                        NaT    NaN      1.00

pandas.core.series.Series

In [24]:
ts
span = (ts_ind[1] - ts) / 5
# span
timestep = pd.to_datetime(ts + np.linspace(1, 5, 5) * span)
timestep
timeseries = pd.Series(timestep, name="timestep")
timeseries
isinstance(timeseries, pd.Series)

Timestamp('2024-06-25 16:45:58.982114')

DatetimeIndex(['2024-06-25 16:45:59.006114', '2024-06-25 16:45:59.030114',
               '2024-06-25 16:45:59.054114', '2024-06-25 16:45:59.078114',
               '2024-06-25 16:45:59.102114'],
              dtype='datetime64[ns]', freq=None)

0   2024-06-25 16:45:59.006114
1   2024-06-25 16:45:59.030114
2   2024-06-25 16:45:59.054114
3   2024-06-25 16:45:59.078114
4   2024-06-25 16:45:59.102114
Name: timestep, dtype: datetime64[ns]

True

In [25]:
# a = len(state) + np.arange(6)
# ar0 = pd.Series(a[:2], name='row0')
# ar1 = pd.Series(a[2:4], name='row1')
# ar2 = pd.Series(a[4:], name='row2')
# series = [ar0, ar1, ar2]
# action = reduce(
#     lambda x, y: pd.merge(x, y, how='outer', left_index=True, right_index=True), series
# )
# action = action.stack().swaplevel(0, 1).sort_index()
# action.name = 'action'
# action
# len(action) + len(state)

In [26]:
reward = (
    pd.DataFrame({"work": len(ss) + len(a), "timestep": ts_ind[0]}, index=[0])
    .stack()
    .swaplevel(0, 1)
    .sort_index()
)
# reward_index = (reward.name,  ts_ind[0], 0)
reward.index.names = ["rows", "idx"]
reward.name = "reward"
reward.index
reward
# reward.name = 'reward'

MultiIndex([('timestep', 0),
            (    'work', 0)],
           names=['rows', 'idx'])

rows      idx
timestep  0      2024-06-25 16:45:59.082114
work      0                              27
Name: reward, dtype: object

In [27]:
reward["work"][0]
reward.loc[("work", 0)]

27

27

In [28]:
# velocity = pd.Series(len(state) + len(action) + len(reward) + s[:4], name='velocity')
# thrust = pd.Series(len(state) + len(action) + len(reward) + s[4:7], name='thrust')
# brake = pd.Series(len(state) + len(action) + len(reward) + s[7:], name='brake')
# series = [velocity, thrust, brake]
# nstate = reduce(
#     lambda x, y: pd.merge(x, y, how='outer', left_index=True, right_index=True), series
# )
# nstate = nstate.stack().swaplevel(0, 1).sort_index()
# nstate.name = 'nstate'
# nstate
# len(nstate)
ts_ind = ts + pd.to_timedelta(5, "s") + pd.to_timedelta(np.arange(0, 4 * 20, 20), "ms")
ts_ind
ss = (
    np.arange(12) + len(ss) + len(a) + len(reward) - 1
)  # exclude the timestamp in reward
a1 = ss[:4]
a2 = ss[4:8]
a3 = ss[8:]
nstate = (
    pd.DataFrame({"timestep": ts_ind, "velocity": a1, "thrust": a2, "brake": a3})
    # .set_index('timestamp')
    .stack()
    .swaplevel(0, 1)
    .sort_index()
)
nstate.name = "nstate"
nstate.index.names = ["rows", "idx"]
len(nstate)
nstate

DatetimeIndex(['2024-06-25 16:46:03.982114', '2024-06-25 16:46:04.002114',
               '2024-06-25 16:46:04.022114', '2024-06-25 16:46:04.042114'],
              dtype='datetime64[ns]', freq=None)

16

rows      idx
brake     0                              36
          1                              37
          2                              38
          3                              39
thrust    0                              32
          1                              33
          2                              34
          3                              35
timestep  0      2024-06-25 16:46:03.982114
          1      2024-06-25 16:46:04.002114
          2      2024-06-25 16:46:04.022114
          3      2024-06-25 16:46:04.042114
velocity  0                              28
          1                              29
          2                              30
          3                              31
Name: nstate, dtype: object

In [29]:
timestamp = pd.Series([ts], name="timestamp")
timestamp.index = pd.MultiIndex.from_product(
    [timestamp.index, [0]], names=["rows", "idx"]
)
timestamp.index
state.index
action.index
reward.index
nstate.index

MultiIndex([(0, 0)],
           names=['rows', 'idx'])

MultiIndex([(   'brake', 0),
            (   'brake', 1),
            (   'brake', 2),
            (   'brake', 3),
            (  'thrust', 0),
            (  'thrust', 1),
            (  'thrust', 2),
            (  'thrust', 3),
            ('timestep', 0),
            ('timestep', 1),
            ('timestep', 2),
            ('timestep', 3),
            ('velocity', 0),
            ('velocity', 1),
            ('velocity', 2),
            ('velocity', 3)],
           names=['rows', 'idx'])

MultiIndex([(      'r0', 0),
            (      'r0', 1),
            (      'r0', 2),
            (      'r0', 3),
            (      'r0', 4),
            (      'r1', 0),
            (      'r1', 1),
            (      'r1', 2),
            (      'r1', 3),
            (      'r1', 4),
            (      'r2', 0),
            (      'r2', 1),
            (      'r2', 2),
            (      'r2', 3),
            (      'r2', 4),
            (   'speed', 0),
            (   'speed', 1),
            (   'speed', 2),
            ('throttle', 0),
            ('throttle', 1),
            ('throttle', 2),
            ('throttle', 3),
            ('throttle', 4),
            ('timestep', 0),
            ('timestep', 1),
            ('timestep', 2)],
           names=['rows', 'idx'])

MultiIndex([('timestep', 0),
            (    'work', 0)],
           names=['rows', 'idx'])

MultiIndex([(   'brake', 0),
            (   'brake', 1),
            (   'brake', 2),
            (   'brake', 3),
            (  'thrust', 0),
            (  'thrust', 1),
            (  'thrust', 2),
            (  'thrust', 3),
            ('timestep', 0),
            ('timestep', 1),
            ('timestep', 2),
            ('timestep', 3),
            ('velocity', 0),
            ('velocity', 1),
            ('velocity', 2),
            ('velocity', 3)],
           names=['rows', 'idx'])

In [30]:
timestamp_index = (timestamp.name, "", 0)
# timestamp_index
state_index = [(state.name, *i) for i in state.index]
# state_index
reward_index = [(reward.name, *i) for i in reward.index]
# reward_index
action_index = [(action.name, *i) for i in action.index]
# action_index
nstate_index = [(nstate.name, *i) for i in nstate.index]
# nstate_index

multiindex = pd.MultiIndex.from_tuples(
    [timestamp_index, *state_index, *action_index, *reward_index, *nstate_index]
)
multiindex

MultiIndex([('timestamp',         '', 0),
            (    'state',    'brake', 0),
            (    'state',    'brake', 1),
            (    'state',    'brake', 2),
            (    'state',    'brake', 3),
            (    'state',   'thrust', 0),
            (    'state',   'thrust', 1),
            (    'state',   'thrust', 2),
            (    'state',   'thrust', 3),
            (    'state', 'timestep', 0),
            (    'state', 'timestep', 1),
            (    'state', 'timestep', 2),
            (    'state', 'timestep', 3),
            (    'state', 'velocity', 0),
            (    'state', 'velocity', 1),
            (    'state', 'velocity', 2),
            (    'state', 'velocity', 3),
            (   'action',       'r0', 0),
            (   'action',       'r0', 1),
            (   'action',       'r0', 2),
            (   'action',       'r0', 3),
            (   'action',       'r0', 4),
            (   'action',       'r1', 0),
            (   'action',       'r

In [31]:
observation_list = [timestamp, state, action, reward, nstate]
observation = pd.concat(observation_list)
observation.index = multiindex
observation
observation.dtype

timestamp            0    2024-06-25 16:45:58.982114
state      brake     0                             8
                     1                             9
                     2                            10
                     3                            11
                                     ...            
nstate     timestep  3    2024-06-25 16:46:04.042114
           velocity  0                            28
                     1                            29
                     2                            30
                     3                            31
Length: 61, dtype: object

dtype('O')

In [32]:
type(observation)
observation

pandas.core.series.Series

timestamp            0    2024-06-25 16:45:58.982114
state      brake     0                             8
                     1                             9
                     2                            10
                     3                            11
                                     ...            
nstate     timestep  3    2024-06-25 16:46:04.042114
           velocity  0                            28
                     1                            29
                     2                            30
                     3                            31
Length: 61, dtype: object

In [33]:
observation0 = observation.copy()
observation0.loc["timestamp", "", 0] = ts + pd.Timedelta(1, "h")
observation1 = observation.copy()
observation1.loc["timestamp", "", 0] = ts + pd.Timedelta(2, "h")
observation2 = observation.copy()
observation2.loc["timestamp", "", 0] = ts + pd.Timedelta(3, "h")
observation3 = observation.copy()
observation3.loc["timestamp", "", 0] = ts + pd.Timedelta(4, "h")
observation4 = observation.copy()
observation4.loc["timestamp", "", 0] = ts + pd.Timedelta(5, "h")
observation_list = [
    observation0,
    observation1,
    observation2,
    observation3,
    observation4,
]

### extract state action reward nstate from list of observations

In [34]:
idx = pd.IndexSlice
observation_list[0]
observation_list[0].index
observation_list[0].loc[idx["state", ["velocity", "thrust", "brake"]]].values
observation_list[0].loc[idx["action", ["r0", "r1", "r2"]]].values
observation_list[0].loc[idx["reward", ["work"]]].values
observation_list[0].loc[idx["nstate", ["velocity", "thrust", "brake"]]].values

timestamp            0    2024-06-25 17:45:58.982114
state      brake     0                             8
                     1                             9
                     2                            10
                     3                            11
                                     ...            
nstate     timestep  3    2024-06-25 16:46:04.042114
           velocity  0                            28
                     1                            29
                     2                            30
                     3                            31
Length: 61, dtype: object

MultiIndex([('timestamp',         '', 0),
            (    'state',    'brake', 0),
            (    'state',    'brake', 1),
            (    'state',    'brake', 2),
            (    'state',    'brake', 3),
            (    'state',   'thrust', 0),
            (    'state',   'thrust', 1),
            (    'state',   'thrust', 2),
            (    'state',   'thrust', 3),
            (    'state', 'timestep', 0),
            (    'state', 'timestep', 1),
            (    'state', 'timestep', 2),
            (    'state', 'timestep', 3),
            (    'state', 'velocity', 0),
            (    'state', 'velocity', 1),
            (    'state', 'velocity', 2),
            (    'state', 'velocity', 3),
            (   'action',       'r0', 0),
            (   'action',       'r0', 1),
            (   'action',       'r0', 2),
            (   'action',       'r0', 3),
            (   'action',       'r0', 4),
            (   'action',       'r1', 0),
            (   'action',       'r

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11], dtype=object)

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26],
      dtype=object)

array([27], dtype=object)

array([28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39], dtype=object)

In [35]:
idx = pd.IndexSlice
state = []
action = []
reward = []
nstate = []
for observation in observation_list:
    state.append(observation.loc[idx["state", ["velocity", "thrust", "brake"]]].values)
    action.append(observation.loc[idx["action", ["r0", "r1", "r2"]]].values)
    reward.append(observation.loc[idx["reward", ["work"]]].values)
    nstate.append(
        observation.loc[idx["nstate", ["velocity", "thrust", "brake"]]].values
    )
npa_state = np.stack(state)
npa_action = np.stack(action)
npa_reward = np.stack(reward)
npa_nstate = np.stack(nstate)
npa_state
npa_action
npa_reward
npa_nstate

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]], dtype=object)

array([[12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26]],
      dtype=object)

array([[27],
       [27],
       [27],
       [27],
       [27]], dtype=object)

array([[28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39]], dtype=object)

In [36]:
npa_state = np.stack(state)
type(npa_state)
npa_state.shape
state_npa = np.array(state)
type(state_npa)
state_npa.shape
npa_state == state_npa
npa_vstate = np.vstack(state)
npa_vstate.shape
type(npa_vstate)

numpy.ndarray

(5, 12)

numpy.ndarray

(5, 12)

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True]])

(5, 12)

numpy.ndarray

In [37]:
npa_nstate

array([[28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39]], dtype=object)

In [38]:
npa_action

array([[12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26]],
      dtype=object)

In [39]:
npa_reward

array([[27],
       [27],
       [27],
       [27],
       [27]], dtype=object)

In [40]:
dfs_epi = pd.concat(observation_list, axis=1).transpose()
dfs_epi.columns.names = ["tuple", "rows", "idx"]
dfs_epi.columns
dfs_epi

MultiIndex([('timestamp',         '', 0),
            (    'state',    'brake', 0),
            (    'state',    'brake', 1),
            (    'state',    'brake', 2),
            (    'state',    'brake', 3),
            (    'state',   'thrust', 0),
            (    'state',   'thrust', 1),
            (    'state',   'thrust', 2),
            (    'state',   'thrust', 3),
            (    'state', 'timestep', 0),
            (    'state', 'timestep', 1),
            (    'state', 'timestep', 2),
            (    'state', 'timestep', 3),
            (    'state', 'velocity', 0),
            (    'state', 'velocity', 1),
            (    'state', 'velocity', 2),
            (    'state', 'velocity', 3),
            (   'action',       'r0', 0),
            (   'action',       'r0', 1),
            (   'action',       'r0', 2),
            (   'action',       'r0', 3),
            (   'action',       'r0', 4),
            (   'action',       'r1', 0),
            (   'action',       'r

tuple                   timestamp state                             \
rows                              brake            thrust            
idx                             0     0  1   2   3      0  1  2  3   
0      2024-06-25 17:45:58.982114     8  9  10  11      4  5  6  7   
1      2024-06-25 18:45:58.982114     8  9  10  11      4  5  6  7   
2      2024-06-25 19:45:58.982114     8  9  10  11      4  5  6  7   
3      2024-06-25 20:45:58.982114     8  9  10  11      4  5  6  7   
4      2024-06-25 21:45:58.982114     8  9  10  11      4  5  6  7   

tuple                              ... nstate                                  \
rows                     timestep  ... thrust                        timestep   
idx                             0  ...      2   3                           0   
0      2024-06-25 16:45:58.982114  ...     34  35  2024-06-25 16:46:03.982114   
1      2024-06-25 16:45:58.982114  ...     34  35  2024-06-25 16:46:03.982114   
2      2024-06-25 16:45:58.982114  ...     34  35  2024-06-25 16:46:03.982114   
3      2024-06-25 16:45:58.982114  ...     34  35  2024-06-25 16:46:03.982114   
4      2024-06-25 16:45:58.982114  ...     34  35  2024-06-25 16:46:03.982114   

tuple                                                          \
rows                                                            
idx                             1                           2   
0      2024-06-25 16:46:04.002114  2024-06-25 16:46:04.022114   
1      2024-06-25 16:46:04.002114  2024-06-25 16:46:04.022114   
2      2024-06-25 16:46:04.002114  2024-06-25 16:46:04.022114   
3      2024-06-25 16:46:04.002114  2024-06-25 16:46:04.022114   
4      2024-06-25 16:46:04.002114  2024-06-25 16:46:04.022114   

tuple                                                   
rows                              velocity              
idx                             3        0   1   2   3  
0      2024-06-25 16:46:04.042114       28  29  30  31  
1      2024-06-25 16:46:04.042114       28  29  30  31  
2      2024-06-25 16:46:04.042114       28  29  30  31  
3      2024-06-25 16:46:04.042114       28  29  30  31  
4      2024-06-25 16:46:04.042114       28  29  30  31  

[5 rows x 61 columns]

In [41]:
dfs_episode1 = dfs_epi.copy().sort_index(axis=1)
dfs_episode1.set_index(("timestamp", "", 0), inplace=True)
dfs_episode1.index.name = "timestamp"
idx = pd.IndexSlice
dfs_episode1

/Users/x/.pyenv/versions/miniconda3-3.11-24.1.2-0/envs/tspace/lib/python3.11/site-packages/pandas/core/indexes/base.py:7588: FutureWarning: Dtype inference on a pandas object (Series, Index, ExtensionArray) is deprecated. The Index constructor will keep the original dtype in the future. Call `infer_objects` on the result to get the old behavior.
  return Index(sequences[0], name=names)


tuple                      action                                      ...  \
rows                           r0                  r1                  ...   
idx                             0   1   2   3   4   0   1   2   3   4  ...   
timestamp                                                              ...   
2024-06-25 17:45:58.982114     12  13  14  15  16  17  18  19  20  21  ...   
2024-06-25 18:45:58.982114     12  13  14  15  16  17  18  19  20  21  ...   
2024-06-25 19:45:58.982114     12  13  14  15  16  17  18  19  20  21  ...   
2024-06-25 20:45:58.982114     12  13  14  15  16  17  18  19  20  21  ...   
2024-06-25 21:45:58.982114     12  13  14  15  16  17  18  19  20  21  ...   

tuple                       state                                 \
rows                       thrust                       timestep   
idx                             2  3                           0   
timestamp                                                          
2024-06-25 17:45:58.982114      6  7  2024-06-25 16:45:58.982114   
2024-06-25 18:45:58.982114      6  7  2024-06-25 16:45:58.982114   
2024-06-25 19:45:58.982114      6  7  2024-06-25 16:45:58.982114   
2024-06-25 20:45:58.982114      6  7  2024-06-25 16:45:58.982114   
2024-06-25 21:45:58.982114      6  7  2024-06-25 16:45:58.982114   

tuple                                                   \
rows                                                     
idx                                                  1   
timestamp                                                
2024-06-25 17:45:58.982114  2024-06-25 16:45:59.002114   
2024-06-25 18:45:58.982114  2024-06-25 16:45:59.002114   
2024-06-25 19:45:58.982114  2024-06-25 16:45:59.002114   
2024-06-25 20:45:58.982114  2024-06-25 16:45:59.002114   
2024-06-25 21:45:58.982114  2024-06-25 16:45:59.002114   

tuple                                                   \
rows                                                     
idx                                                  2   
timestamp                                                
2024-06-25 17:45:58.982114  2024-06-25 16:45:59.022114   
2024-06-25 18:45:58.982114  2024-06-25 16:45:59.022114   
2024-06-25 19:45:58.982114  2024-06-25 16:45:59.022114   
2024-06-25 20:45:58.982114  2024-06-25 16:45:59.022114   
2024-06-25 21:45:58.982114  2024-06-25 16:45:59.022114   

tuple                                                                     
rows                                                   velocity           
idx                                                  3        0  1  2  3  
timestamp                                                                 
2024-06-25 17:45:58.982114  2024-06-25 16:45:59.042114        0  1  2  3  
2024-06-25 18:45:58.982114  2024-06-25 16:45:59.042114        0  1  2  3  
2024-06-25 19:45:58.982114  2024-06-25 16:45:59.042114        0  1  2  3  
2024-06-25 20:45:58.982114  2024-06-25 16:45:59.042114        0  1  2  3  
2024-06-25 21:45:58.982114  2024-06-25 16:45:59.042114        0  1  2  3  

[5 rows x 60 columns]

In [42]:
dfs_episode1.loc[:, idx["action":"state", :, :, :]] = dfs_episode1.loc[
    :, idx["action":"state", :, :, :]
].astype("int")
dfs_episode1
dfs_episode1.dtypes
dfs_episode1.columns

TypeError: int() argument must be a string, a bytes-like object or a real number, not 'Timestamp'

### Convert columns types to float

In [ ]:
dfs_epi
dfs_episode = dfs_epi.copy()
dfs_episode.index
dfs_episode.set_index(("timestamp", "", 0), inplace=True)
dfs_episode.sort_index(axis=1, inplace=True)
dfs_episode.index
dfs_episode

In [ ]:
dfs_episode.index.name = "timestamp"
idx = pd.IndexSlice

# # dfs_episode = dfs_episode.astype({idx['state', 'velocity', :]: 'int'})  # Error unhashable type: 'slice' for dictionary
# # sorted_idx = **(idx['state', :, :]:'int')
# # sorted_idx
# dfs_episode.loc[:, idx['state', ['brake', 'thrust', 'velocity'], :]] = dfs_episode.loc[
#     :, idx['state', ['brake', 'thrust', 'velocity'], :]
# ].astype(
#     'float'
# )  # float16 not allowed in parquet
#
# dfs_episode.loc[:, idx['action', ['r0', 'r1', 'r2'], :]] = dfs_episode.loc[
#     :, idx['action', ['r0', 'r1', 'r2'], :]
# ].astype(
#     'float'
# )  # float16 not allowed in parquet
# # dfs_episode['action'] = dfs_episode['action'].astype('float')
# # dfs_episode['reward'] = dfs_episode['reward'].astype('float')
# dfs_episode.loc[:, idx['reward', 'work', 0]] = dfs_episode.loc[
#     :, idx['reward', 'work', 0]
# ].astype(
#     'float'
# )  # float16 not allowed in parquet
#
# # dfs_episode['nstate'] = dfs_episode['nstate'].astype('float')
# dfs_episode.loc[:, idx['nstate', ['brake', 'thrust', 'velocity'], :]] = dfs_episode.loc[
#     :, idx['nstate', ['brake', 'thrust', 'velocity'], :]
# ].astype(
#     'float'
# )  # float16 not allowed in parquet
state_cols_float = [("state", col) for col in ["brake", "thrust", "velocity"]]
action_cols_float = [("action", col) for col in ["r0", "r1", "r2", "speed", "throttle"]]
reward_cols_float = [("reward", "work")]
nstate_cols_float = [("nstate", col) for col in ["brake", "thrust", "velocity"]]
for col in action_cols_float + state_cols_float + reward_cols_float + nstate_cols_float:
    dfs_episode[col[0], col[1]] = dfs_episode[col[0], col[1]].astype(
        "float"
    )  # float16 not allowed in parquet
dfs_episode
dfs_episode.dtypes
# dfs_episode.columns
# dfs_epi
# dfs_episode

## prepend two levels of index "vehicle" and "driver" to the DataFrame object

In [ ]:
dfs_episode = pd.concat(
    [dfs_episode], keys=[drivers_by_id["wang-cheng"].pid], names=["driver"]
)
dfs_episode = pd.concat(
    [dfs_episode], keys=[trucks_by_id["VB7"].vid], names=["vehicle"]
)

In [ ]:
dfs_episode.index
dfs_episode.columns

In [ ]:
# dfs_episode.columns.set_names(
#     [
#         'tuple',
#         'rows',
#         'idx',
#     ],
#     level=[0, 1, 2],
#     inplace=True,
# )
dfs_episode
dfs_episode.dtypes

In [ ]:
# dfs_episode['state', 'thrust'] = dfs_episode['state', 'thrust'].astype('float')
# # dfs_episode.loc[:, idx['state', ['brake', 'thrust', 'velocity'], :]] = dfs_episode.loc[
# #     :, idx['state', ['brake', 'thrust', 'velocity'], :]
# # ].astype(
# #     'float'
# # )  # float16 not allowed in parquet
# dfs_episode.loc[:, ('state', ['brake', 'thrust', 'velocity'])] = dfs_episode.loc[
#     :, ('state', ['brake', 'thrust', 'velocity'])
# ].astype(
#     'float'
# )  # float16 not allowed in parquet
# dfs_episode['action', 'r0'] = dfs_episode['action', 'r0'].astype(
#     'float'
# )  # float16 not allowed in parquet
#
# dfs_episode.dtypes

In [ ]:
# idx = pd.IndexSlice
# dfs_episode.loc[:, idx['state', :, :]] = dfs_episode.loc[:, idx['state', :, :]].astype(
#     'int'
# )
# dfs_episode.loc[:, idx['action', :, :]] = dfs_episode.loc[
#     :, idx['action', :, :]
# ].astype('float16')
# dfs_episode.loc[:, idx['reward', :, :]] = dfs_episode.loc[
#     :, idx['reward', :, :]
# ].astype('float16')
# dfs_episode.loc[:, idx['nstate', :, :]] = dfs_episode.loc[
#     :, idx['nstate', :, :]
# ].astype('float16')
#
# vel_1 = dfs_episode[[('state', 'velocity', 1)]]
# vel_1.dtypes
# vel_1.index
# vel_1.values
# # type(vel_1)
# vel_1.iloc[0]
# type(vel_1.iloc[0])
# type(vel_1.iloc[0].values[0])

## Add a level of index for episode

In [ ]:
episodestart = ts - pd.Timedelta(1, "h")
dfs_episode = pd.concat([dfs_episode], keys=[ts], names=["episodestart"])
dfs_episode = dfs_episode.swaplevel(1, 0, axis=0)
dfs_episode = dfs_episode.swaplevel(1, 2, axis=0)
dfs_episode.sort_index(inplace=True)
dfs_episode.index
dfs_episode.columns
dfs_episode

In [ ]:
dfs_episode.dtypes

In [ ]:
vb7 = trucks_by_id["VB7"]

In [ ]:
from eos.data_io.eos_struct import PoolQuery

query = PoolQuery(
    site=trucks_by_id["VB7"].site,
    vehicle=trucks_by_id["VB7"].vid,
    driver=drivers_by_id["zheng-longfei"].pid,
    start=episodestart,
    end=ts,
)
isinstance(query, dict)

In [ ]:
ts_new = pd.to_datetime((datetime.now()))
ts_new
episodestart = ts_new - pd.Timedelta(2, "d")
episodestart

dfs_episode0 = dfs_episode.copy()
dfs_episode0.index = dfs_episode0.index.set_levels([episodestart], level="episodestart")
dfs_episode0.index = dfs_episode0.index.set_levels(
    [[trucks_by_id["VB7"].vid], [drivers_by_id["zheng-longfei"].pid]],
    level=["vehicle", "driver"],
    verify_integrity=False,
)
dfs_episode1 = dfs_episode.copy()
dfs_episode1.index = dfs_episode1.index.set_levels(
    [episodestart - pd.Timedelta(3, "d")], level="episodestart"
)
dfs_episode1.index = dfs_episode1.index.set_levels(
    [[trucks_by_id["MP73"].vid], [drivers_by_id["wang-cheng"].pid]],
    level=["vehicle", "driver"],
    verify_integrity=False,
)
dfs_episode2 = dfs_episode.copy()
dfs_episode2.index = dfs_episode2.index.set_levels(
    [episodestart - pd.Timedelta(4, "d")], level="episodestart"
)
dfs_episode2.index = dfs_episode2.index.set_levels(
    [[trucks_by_id["VB7"].vid], [drivers_by_id["wang-cheng"].pid]],
    level=["vehicle", "driver"],
    verify_integrity=False,
)
dfs_episode3 = dfs_episode.copy()
dfs_episode3.index = dfs_episode3.index.set_levels(
    [episodestart - pd.Timedelta(5, "d")], level="episodestart"
)
dfs_episode3.index = dfs_episode3.index.set_levels(
    [[trucks_by_id["MP73"].vid], [drivers_by_id["zheng-longfei"].pid]],
    level=["vehicle", "driver"],
    verify_integrity=False,
)
dfs_episode0

In [ ]:
# dfs_episode_concat = pd.concat([dfs_episode, dfs_episode0], axis=0)
# display('dfs_episode_concat')
# dfs_episode_concat.index
# dfs_episode_concat.columns

In [ ]:
from functools import reduce

episodes = [dfs_episode, dfs_episode0, dfs_episode1, dfs_episode2, dfs_episode3]
try:
    dfs_episode_all = reduce(
        lambda left, right,: pd.concat([left, right], axis=0), episodes
    )
except Exception as e:
    print(e)
# dfs_episode_all.sort_index(inplace=True)
dfs_episode_all = dfs_episode_all.swaplevel(1, 0, axis=0)
dfs_episode_all = dfs_episode_all.swaplevel(1, 2, axis=0)
dfs_episode_all.sort_index(inplace=True)
dfs_episode_all = dfs_episode_all[["state", "action", "reward", "nstate"]]
display("dfs_episode_all")
dfs_episode_all.index
dfs_episode_all.columns

## Make MultiIndex to Rows by adding levels of "Vehicle" and "Driver"

###  reset index to move vehicle and driver to columns, preprocessing for dask manipulation

In [ ]:
dfs_episodes = dfs_episode_all.reset_index(
    level=["vehicle", "driver"]
)  # unstack vehicle and driver to columns in level 0 with default '' in level 1
# # dfs_episodes.columns
# # dfs_episode0.index = dfs_episode0.index.set_levels([[trucks[0].vid],[drivers[1].pid]], level=['vehicle', 'driver'], verify_integrity=False)
# old_columns = dfs_episodes.columns
# # old_columns[0]= (old_columns[0][0],0)
# new_columns_tuples = [(old_columns[0][0],0), (old_columns[1][0],0)] + old_columns[2:].to_list()
# prepend_columns = pd.MultiIndex.from_tuples(new_columns_tuples, names=old_columns.names)
# # prepend_columns

# dfs_episodes.columns = prepend_columns
dfs_episodes
# dfs_episodes.columns
# dfs_episodes.dtypes
# dfs_episode_all

In [ ]:
dfs_episodes.dtypes

In [ ]:
dfs_episodes.columns

In [ ]:
dfs_episodes["vehicle"] = dfs_episodes["vehicle"].astype("category")
dfs_episodes["driver"] = dfs_episodes["driver"].astype("category")
# dfs_episodes.dtypes
# dfs_episodes.columns
# dfs_episodes[['vehicle','driver']].dtypes
# dfs_episodes[['vehicle','driver']]
# dfs_episodes[['vehicle','driver']].iloc[:3].dtypes
# sliced = dfs_episodes[['vehicle']].iloc[:3].stack(level=[-1,-2])
# type(sliced)
# sliced.index
# sliced.values

dfs_episodes_sorted = dfs_episodes.sort_index(
    axis=1, level=[0, 1, 2], ascending=[True, True, True]
)
dfs_episodes_sorted.sort_index(axis=0, inplace=True)
# dfs_episodes_sorted = dfs_episodes.sort_index(axis=1, level=[0,1], ascending=[True, True])
# dfs_episodes_sorted = dfs_episodes.sort_index(axis=0, level=[0,1], ascending=[True, True])
# dfs_episodes_sorted.sort_index(axis=1,inplace=True)
dfs_episodes_sorted
dfs_episodes_sorted.columns

# dfs_episodes[['driver'], ['vehicle']] = dfs_episodes[['driver', 'vehicle']].apply(lambda x: x.cat.codes)

## dataframe slicing

In [ ]:
ts
ep_start = ts - pd.Timedelta(9, "D")
ep_start
# time_slice
episode_slice = pd.date_range(ep_start, periods=6, freq="D")
episode_slice

In [ ]:
timestamp_slice = pd.date_range(ts, periods=3, freq="H") + pd.Timedelta(10, "min")
timestamp_slice

In [ ]:
dfs_episodes_sorted

In [ ]:
dfs_episodes_sorted.index
dfs_episodes_sorted.columns

In [ ]:
# dfs_episode_all.loc['VB7', 'zheng-longfei', episode_slice[0]:episode_slice[3]]
# dfs_selected_episodes = dfs_episodes_sorted.loc[trucks[0].vid, drivers[1].pid, episode_slice[0]:episode_slice[3], timestamp_slice[0]:timestamp_slice[2]]
idx = pd.IndexSlice
dfs_selected_episodes = dfs_episodes_sorted.loc[
    idx[episode_slice[0] : episode_slice[5], timestamp_slice[0] : timestamp_slice[2]],
    idx["action":"driver"],
]
dfs_selected_episodes
# dfs_selected_episodes[['action', 'reward']]

In [ ]:
# dfs_selected_episodes_columns = dfs_episode_all.loc['VB7', 'zheng-longfei', episode_slice[0]:episode_slice[3], timestamp_slice[0]:timestamp_slice[2]][['action', 'reward']]
# dfs_selected_episodes_columns

In [ ]:
# dfs_episode_all_sorted = dfs_episode_all.sort_index(axis=1)
# dfs_episode_all_sorted = dfs_episode_all_sorted.sort_index(axis=0)
# dfs_episode_all_sorted

In [ ]:
# dfs_selected_episodes_columns = dfs_episode_all_sorted.loc[(slice('VB6'), slice('wang-cheng'), slice(None), slice(None)),:]
# idx = pd.IndexSlice
# dfs_episode_all_sorted.loc[(idx['VB6'], idx['wang-cheng','zheng-longfei'], slice(None), slice(None)),:]
# dfs_selected_episodes_columns = dfs_episode_all_sorted.loc[(idx['VB7'], idx['zheng-longfei'], slice(None), slice(None)),['state','n_state']]
# dfs_selected_episodes_columns = dfs_episodes_sorted.loc[(idx['VB7'], idx['zheng-longfei'], slice(None), slice(None)),['state','n_state']]
# dfs_selected_episodes_columns

In [ ]:
ts_new = pd.to_datetime((datetime.now()))
episodestart = ts_new - pd.Timedelta(10, "d") - pd.Timedelta(6, "h")
episodestart
episode_slice = pd.date_range(episodestart, periods=20, freq="d") + pd.Timedelta(
    10, "min"
)
episode_slice
ts
time_slice = pd.date_range(ts, periods=6, freq="h") - pd.Timedelta(10, "min")
time_slice

In [ ]:
episode_slice[4]: episode_slice[8]
idx[episode_slice[4] : episode_slice[8]]
idx[episode_slice[4] : episode_slice[8], slice(None)]

In [ ]:
episode_slice[4]
episode_slice[11]
# dfs_selected_episodes = dfs_episodes_sorted.loc[idx['VB7'], slice(None), episode_slice[4]:episode_slice[11]]
# dfs_selected_episodes
# dfs_selected_episodes = dfs_episodes_sorted.loc[slice(None), idx['zheng-longfei'], episode_slice[4]:episode_slice[11]]
# dfs_selected_episodes
# dfs_selected_episodes = dfs_episode_all.loc[slice(None), idx['zheng-longfei'], episode_slice[4]:episode_slice[11], time_slice[0]:time_slice[3]]
# dfs_selected_episodes
# epislice = idx(episode_slice[4]:episode_slice[11])

# dfs_selected_episodes = dfs_episodes_sorted.loc[idx[episode_slice[4]:episode_slice[11],slice(None)], idx[dfs_episodes_sorted['driver']==drivers[0].pid]]
dfs_selected_episodes1 = dfs_episodes_sorted.loc[
    dfs_episodes_sorted["driver"] == drivers_by_id["wang-cheng"].pid
]
dfs_selected_episodes1
dfs_selected_episodes2 = dfs_episodes_sorted.loc[
    dfs_episodes_sorted["driver"] == drivers_by_id["wang-cheng"].pid
].loc[idx[episode_slice[4] : episode_slice[8]]]
dfs_selected_episodes2
dfs_selected_episodes3 = dfs_episodes_sorted.loc[
    (dfs_episodes_sorted["driver"] == drivers_by_id["wang-cheng"].pid)
    & (dfs_episodes_sorted["vehicle"] == trucks_by_id["VB7"].vid)
].loc[idx[episode_slice[4] : episode_slice[8]]]
dfs_selected_episodes3
# dfs_selected_episodes31 = dfs_episodes_sorted.loc[idx[episode_slice[4]:episode_slice[8],slice(None)]].loc[ (dfs_episodes_sorted['driver']==drivers[0].pid) & (dfs_episodes_sorted['vehicle']==trucks[0].vid)]
# dfs_selected_episodes31 = dfs_episodes_sorted.loc[ (dfs_episodes_sorted['driver']==drivers[0].pid) & (dfs_episodes_sorted['vehicle']==trucks[0].vid) & (idx[episode_slice[4]:episode_slice[8],slice(None)])]
# dfs_selected_episodes31
# dfs_selected_episodes3.index
# dfs_selected_episodes3.columns
# dfs_selected_episodes = dfs_episodes_sorted.loc[slice(None), idx['zheng-longfei'], episode_slice[4]:episode_slice[11]]
# dfs_selected_episodes
# dfs_selected_episodes = dfs_episode_all.loc[slice(None), idx['zheng-longfei'], episode_slice[4]:episode_slice[11], time_slice[0]:time_slice[3]]
# dfs_selected_episodes

In [ ]:
idx[time_slice[0] : time_slice[3]]
dfs_selected_episodes3.columns

In [ ]:
time_slice2 = pd.date_range(ts, periods=6, freq="S")
time_slice2
dfs_selected_episodes3_sorted = dfs_selected_episodes3.sort_index(axis=0).sort_index(
    axis=1
)[["action"]]
dfs_selected_episodes3_sorted
# dfs_selected_episodes3.loc[:, idx[:, :, 0:2, :]]
# dfs_selected_episodes3_sorted.loc[:, idx[:, :,time_slice2[0]:time_slice2[1], :]]
# dfs_selected_episodes3.loc[idx[:,time_slice[0]:time_slice[2]],:]
dfs_selected_episodes3.loc[idx[:, time_slice[0] : time_slice[3]], :]

In [ ]:
dfs_selected_episodes3.index
# dfs_selected_episodes3.columns
time_slice[0]
time_slice[3]
idx[:, time_slice[0] : time_slice[3]]
dfs_selected_episodes4 = dfs_selected_episodes3.loc[
    idx[:, time_slice[0] : time_slice[3]], :
]
# dfs_selected_episodes4 = dfs_selected_episodes3.loc[idx[:,time_slice[0]:time_slice[3],:],:]

dfs_selected_episodes4
dfs_selected_episodes41 = dfs_selected_episodes3.loc[
    idx[:, time_slice[0] : time_slice[3]], "action":"driver"
]
dfs_selected_episodes41
# dfs_selected_episodes4 = dfs_episodes_sorted.loc[ (dfs_episodes_sorted['driver']==drivers[0].pid) & (dfs_episodes_sorted['vehicle']==trucks[0].vid)].loc[idx[episode_slice[4]:episode_slice[8],time_slice[0]:time_slice[3]]]
# dfs_selected_episodes4

In [ ]:
# dfs_selected_episodes = dfs_episode_all.loc['VB7', 'zheng-longfei', episode_slice[0]:episode_slice[3], timestamp_slice[0]:timestamp_slice[2]]
# dfs_selected_episodes_columns = dfs_episode_all_sorted.loc[(idx['VB7'], idx['zheng-longfei'], slice(None), slice(None)),['state','n_state']]
# dfs_selected_episodes_columns

In [ ]:
dfs_episodes_sorted
# dfs_episode.loc[:,'state']
dfs_slice = dfs_episodes_sorted.loc[
    dfs_episodes_sorted["vehicle"] == "MP73", ["vehicle", "driver", "state", "reward"]
]
dfs_slice

# Saved episodes as parquet in multi-level folders "vehicle/driver/episode/tuple.parquet"

In [ ]:
import os
import dask.dataframe as dd
from dask.diagnostics import ProgressBar
import numpy as np
import pandas as pd
from datetime import datetime

import pyarrow as pa
import pyarrow.parquet as pq
import platform

print("Python: ", platform.python_version())
print("pandas: ", pd.__version__)
print("pyarrow: ", pa.__version__)

In [ ]:
os.chdir("../../data")

In [ ]:
os.getcwd()

## create parquet files

In [ ]:
dfs_episodes_sorted
dfs_episodes_sorted.index
dfs_episodes_sorted.columns
dfs_episodes_sorted.dtypes

In [ ]:
dfs_complete_episodes = dfs_episodes_sorted.reset_index("episodestart")
dfs_complete_episodes
dfs_complete_episodes.index
dfs_complete_episodes.columns

In [ ]:
# dfs_episode4dask = dfs_episode_all_sorted.swaplevel(0,-1, axis=0).swaplevel(1,3, axis=0).swaplevel(2,3, axis=0).unstack()
# dfs_episode4dask = dfs_episode4dask.swaplevel(0,-1, axis=1).swaplevel(-2,-1, axis=1)
# dfs_episode4dask
# # dfs_episode4dask = dfs_episode4dask.swaplevel(0,-1, axis=1).swaplevel(-2,-1, axis=1)
# # dfs_episode4dask.index
# # dfs_episode4dask.index
# # dfs_episode4dask.columns
# # dfs_episode4dask
# # dfs_episode_all_stack = dfs_episode_all.unstack(level=[-1,-2,-3,])
# # dfs_episode_all_stack

In [ ]:
# dfs_episode4dask1 = dfs_episode4dask.unstack().swaplevel(-2,-1, axis=1).swaplevel(-2,-3,axis=1).swaplevel(-3,-4,axis=1)
# # dfs_episode4dask1
# dfs_episode4dask2 = dfs_episode4dask1.unstack().swaplevel(-2,-1, axis=1).swaplevel(-2,-3,axis=1).swaplevel(-3,-4,axis=1).swaplevel(-4,-5,axis=1)
# dfs_episode4dask2.sort_index(axis=1, inplace=True)
# dfs_episode4dask2

### encoding multiindex dataframe to flat index for Dask DataFrame

In [ ]:
dfs_complete_episodes.columns
cols = dfs_complete_episodes.columns.to_flat_index()
cols

## 3 level index
# cols_str = [
#     f'{x[0]}_{x[1]}_{x[2]}'
#     if (x[1] != '')
#     else f'{x[0]}__{x[2]}'
#     if (x[2] != '')
#     else f'{x[0]}'
#     for x in cols
# ]

## 4 level index
cols_str = [
    f"{x[0]}_{x[1]}_{x[2]}"
    if (x[1] != "" and x[2] != "")
    else f"{x[0]}_{x[1]}_"
    if (x[1] != "" and x[2] == "")
    else f"{x[0]}__{x[2]}"
    if (x[2] != "")
    else f"{x[0]}__"
    for x in cols
]
cols_str

In [ ]:
# encoding index and columns
dfs_complete_episodes_flat = dfs_complete_episodes.copy()
cols = dfs_complete_episodes.columns.to_flat_index()
dfs_complete_episodes_flat.columns = [
    f"{x[0]}_{x[1]}_{x[2]}"
    if (x[1] != "" and x[2] != "")
    else f"{x[0]}_{x[1]}_"
    if (x[1] != "" and x[2] == "")
    else f"{x[0]}__{x[2]}"
    if (x[2] != "")
    else f"{x[0]}__"
    for x in cols
]
dfs_complete_episodes_flat

In [ ]:
dfs_complete_episodes_flat
dfs_complete_episodes_flat.dtypes

In [ ]:
dfs_complete_episodes_flat["vehicle__"].iloc[0:2].values.dtype
dfs_complete_episodes_flat["vehicle__"].dtype
dfs_complete_episodes_flat["state_velocity_0"].dtype

In [ ]:
try:
    ddf_episodes = dd.from_pandas(dfs_complete_episodes_flat, npartitions=1)
except Exception as e:
    print(e)

try:
    ddf_episodes.index
    ddf_episodes.columns
except Exception as e:
    print(e)

ddf_episodes

In [ ]:
custom_metadata = {
    b"eos": b'{"length":[3, 600, 5],"timezeone":"sh","units":["kph","pct","pct"],"data_propensity":[50, 1, 4],"Dataset Description": "MP vehicle from TBox"}'
}
custom_metadata

In [ ]:
try:
    with ProgressBar():
        ddf_episodes.to_parquet(
            "eos_complete_episodes",
            engine="pyarrow",
            compression="snappy",
            partition_on=["vehicle__", "driver__", "episodestart__"],
            write_metadata_file=True,
            custom_metadata=custom_metadata,
        )
except Exception as e:
    print(e)

### Read saved parquet file

In [ ]:
ddf = dd.read_parquet(
    "eos_complete_episodes",
    engine="pyarrow",
    compression="snappy",
    ignore_metadata_file=False,
    infer_divisions=True,
)
ddf.head(5)
ddf.dtypes
ddf.npartitions
ddf.divisions
ddf._meta

### Get customized metadata with pyarrow

In [ ]:
import pyarrow as pa
import pyarrow.parquet as pq
import json

# print('pyarrow: ', pa.__version__)

# table = pq.read_table('ddf_episodes')
# table_meta = table.schema.metadata[b'eos']
# print(table_meta)
# # custom_metadata_info = json.loads(table.schema.metadata[b'eos'])
# # print(custom_metadata_info)
# try:
#     custom_meta_info = json.loads(table_meta)
# except Exception as e:
#     print(f'Exception: {e}')

# print(custom_meta_info)

# # Print formatted output of the dichtionary custom_meta_info:
# for key, val in custom_meta_info.items():
#     print('{:15}: {}'.format(key, val))

# ALTERNATE:

table_meta = pq.read_metadata("eos_complete_episodes/_common_metadata")
# print(table_meta)
# print(table_meta.metadata[b'eos'])
custom_meta_info = table_meta.metadata[b"eos"]
custom_meta_info = json.loads(custom_meta_info)
# custom_meta_info

for key, val in custom_meta_info.items():
    print(f"{key}: {val}")

# table_meta = pq.read_metadata('ddf_episodes/_metadata')
# # print(table_meta)
# # print(table_meta.metadata[b'eos'])
# custom_meta_info = table_meta.metadata[b'eos']
# custom_meta_info = json.loads(custom_meta_info)
# custom_meta_info

### encoding flat_index of dask dataframe to multiindex

In [ ]:
df_episodes_read = ddf.compute()
df_episodes_read

In [ ]:
# decoding
multi_cols = [tuple(col.split("_")) for col in df_episodes_read.columns]
multi_cols
# multi_cols = [(col[0], int(col[1])) if len(col)==2 else col for col in multi_cols]
# multi_cols
df_episodes_read_multicol = df_episodes_read.copy()
multi_idx = pd.MultiIndex.from_tuples(multi_cols)
# multi_idx
multi_idx.names = ["tuple", "rows", "idx"]
driver_vehicle = [
    idx
    for idx in multi_idx
    if idx[0] == "driver" or idx[0] == "vehicle" or idx[0] == "episodestart"
]
driver_vehicle
# multi_idx = multi_idx.set_levels([multi_idx.levels[0], multi_idx.levels[1].astype(int)])
# multi_idx

In [ ]:
# pd.Series([1, np.nan,2,None])
# pd.Series([1,np.nan,2,None,pd.NA])

In [ ]:
# decoding columns
from datetime import datetime

multi_tpl = [tuple(col.split("_")) for col in df_episodes_read.columns]
# multi_tpl
# multi_cols = [(col[0], int(col[1])) if len(col)==2 else col for col in multi_cols]
# multi_cols
df_episodes_read_multicol = df_episodes_read.copy()
multi_col = pd.MultiIndex.from_tuples(multi_tpl)
# multi_idx
# multi_col
i1 = multi_col.get_level_values(0)
i1 = [
    "" if str(idx) in (str(pd.NA), "nan", "") else idx for idx in i1
]  # convert index of level 2 type to int and '' if NA
i1
# i2 = multi_col.get_level_values(1).fillna('') # must be null string instead of the default pd.NA or np.nan
# i2 = [idx if isinstance(idx, int) else '' for idx in i2]
i2 = multi_col.get_level_values(
    1
)  # must be null string instead of the default pd.NA or np.nan
i2 = [
    "" if str(idx) in (str(pd.NA), "nan", "") else idx for idx in i2
]  # convert index of level 2 type to int and '' if NA
i2
# i2 = [idx if isinstance(idx, str) else '' for idx in i2]
# i2.astype('int')
i3 = multi_col.get_level_values(
    2
)  # must be null string instead of the default pd.NA or np.nan
i3 = [
    "" if str(idx) in (str(pd.NA), "nan", "") else int(idx) for idx in i3
]  # convert index of level 2 type to int and '' if NA
i3


multi_col = pd.MultiIndex.from_arrays([i1, i2, i3])
multi_col.names = ["tuple", "rows", "idx"]
multi_col


# i2[-1]
# i2.dropna()
# i2
# l2 = ['' if i==nan else i  for i in i2]
# l2
# i2= i2[:-2].astype('int')
# i2 = i2.append(pd.Index(['','']))
# l2 = [''] + list(l2.values[:-1])
# print(l2)
# arrays = [ for i2 in l2 for i1 in l1]
# l2 = l2[:-2].astype('int') + ['', '']
# multi_col.set_levels(ll, level=['tuple','step'])
# driver_vehicle = [idx for idx in multi_idx if idx[0]=='driver' or idx[0]=='vehicle']
# multi_tpl =  [(col[0],)  if col[0]=='driver' or col[0]=='vehicle' else (col[0],int(col[1])) for col in multi_col]
# multi_idx1 = pd.MultiIndex.from_tuples(multi_idx1)
# multi_idx = multi_idx.set_levels([multi_idx.levels[0], multi_idx.levels[1].astype(int)])
# multi_col = pd.MultiIndex.from_tuples(multi_tpl)
# multi_col

In [ ]:
# # decoding index
# multi_tuple = [tuple(idx.split('_')) for idx in df_episodes_read.index]
# multi_idx = pd.MultiIndex.from_tuples(multi_tuple)
# # multi_idx
# i0 = multi_idx.get_level_values(
#     0
# )  # must be null string instead of the default pd.NA or np.nan
# i0 = [
#     ''
#     if str(idx) in (str(pd.NA), 'nan', '')
#     else datetime.strptime(idx, '%Y-%m-%dT%H:%M:%S.%f')
#     for idx in i0
# ]  # convert index of level 2 type to int and '' if NA
# i1 = multi_idx.get_level_values(
#     1
# )  # must be null string instead of the default pd.NA or np.nan
# i1 = [
#     ''
#     if str(idx) in (str(pd.NA), 'nan', '')
#     else datetime.strptime(idx, '%Y-%m-%dT%H:%M:%S.%f')
#     for idx in i1
# ]  # convert index of level 2 type to int and '' if NA
# df_episodes_read_multiidx = df_episodes_read.copy()
# multi_idx = pd.MultiIndex.from_arrays([i0, i1], names=('episodestart', 'timestamp'))
#
# multi_idx.dtypes
# multi_idx
# len(multi_idx)

In [ ]:
df_episodes_read_multi = df_episodes_read.copy()
df_episodes_read_multi.columns = multi_col
# df_episodes_read_multi.index = multi_idx
df_episodes_read_multi
df_episodes_read_multi.columns
df_episodes_read_multi.index
df_episodes_read_multi.dtypes

### recover deep multiindex from columns ['vehicle','driver','episodestart']

In [ ]:
df_episodes_read_multi_setindex = df_episodes_read_multi.set_index(
    ["vehicle", "driver", "episodestart", df_episodes_read_multi.index]
)
# df_episodes_read_multi_setindex
# df_episodes_read_multi_setindex.sort_index(inplace=True)
df_episodes_read_multi_setindex = df_episodes_read_multi_setindex.swaplevel(
    1, 2, axis=0
).swaplevel(0, 1, axis=0)
# df_episodes_read_multi_setindex.index
# df_episodes_read_multi_setindex.columns
df_episodes_read_multi_setindex

## append new episode to the specific parquet file

In [ ]:
dfs_episode4 = dfs_episode.copy()
dfs_episode4.index = dfs_episode3.index.set_levels(
    [episodestart - pd.Timedelta(8, "d")], level="episodestart"
)
dfs_episode4.index = dfs_episode3.index.set_levels(
    [[trucks_by_id["VB4"].vid], [drivers_by_id["zheng-longfei"].pid]],
    level=["vehicle", "driver"],
    verify_integrity=False,
)
# dfs_episode4
dfs_episode4 = dfs_episode4.swaplevel(1, 2, axis=0).swaplevel(0, 1, axis=0)
dfs_episode4

# dfs_episode5 = dfs_episode.copy()
# dfs_episode5.index = dfs_episode3.index.set_levels([episodestart-pd.Timedelta(9,'d')], level='episode')
# df_episodes_read_multi_setindex.columns
# df_episodes_read_multi_setindex

In [ ]:
dfs_episodes_new = pd.concat([df_episodes_read_multi_setindex, dfs_episode4], axis=0)
dfs_episodes_new.index.names = ["episodestart", "vehicle", "driver", "timestamp"]
dfs_episodes_new
dfs_episodes_new.columns
dfs_episodes_new.index

#### save new dataframe back to parquet

In [ ]:
os.getcwd()

In [ ]:
dfs_episodes_new_flat = dfs_episodes_new.copy()
dfs_episodes_new_flat = dfs_episodes_new_flat.reset_index(
    level=["vehicle", "driver", "episodestart"]
)
dfs_episodes_new_flat.columns
dfs_episodes_new_flat.index
dfs_episodes_new_flat

In [ ]:
# encoding index
# from datetime import datetime

# flat_idx = dfs_episodes_new_flat.index.to_flat_index()
# flat_idx = [
#     f'{x[0].strftime("%Y-%m-%dT%H:%M:%S.%f")}_{x[1].strftime("%Y-%m-%dT%H:%M:%S.%f")}'
#     if x[1] != ''
#     else f'{x[0].strftime("%Y-%m-%dT%H:%M:%S.%f")}'
#     for x in flat_idx
# ]
# # flat_idx

# encoding columns
flat_cols = dfs_episodes_new_flat.columns.to_flat_index()
# flat_cols
# flat_cols = [
#     f'{x[0]}_{x[1]}_{x[2].strftime("%Y-%m-%dT%H:%M:%S.%f")}_{x[3]}'
#     if (x[1] != '' and x[3] not in ('', pd.NaT, str(pd.NA)))
#     else f'{x[0]}_{x[1]}_{x[2].strftime("%Y-%m-%dT%H:%M:%S.%f")}_'
#     if (x[1] != '' and x[3] in ('', pd.NaT, str(pd.NA)))
#     else f'{x[0]}__{x[2].strftime("%Y-%m-%dT%H:%M:%S.%f")}_'
#     if (x[2] not in ('', pd.NaT, str(pd.NA)))
#     else f'{x[0]}___'
#     for x in flat_cols
# ]
flat_cols = [
    f"{x[0]}_{x[1]}_{x[2]}"
    if (x[1] != "" and x[2] not in ("", pd.NaT, str(pd.NA)))
    else f"{x[0]}_{x[1]}_"
    if (x[1] != "" and x[2] in ("", pd.NaT, str(pd.NA)))
    else f"{x[0]}__{x[2]}"
    if (x[2] not in ("", pd.NaT, str(pd.NA)))
    else f"{x[0]}__"
    for x in flat_cols
]
flat_cols

In [ ]:
dfs_episodes_new_flat.columns = flat_cols
# dfs_episodes_new_flat.index = flat_idx
dfs_episodes_new_flat["vehicle__"] = dfs_episodes_new_flat["vehicle__"].astype(
    "category"
)
dfs_episodes_new_flat["driver__"] = dfs_episodes_new_flat["driver__"].astype("category")
dfs_episodes_new_flat["episodestart__"] = dfs_episodes_new_flat[
    "episodestart__"
].astype("datetime64[ns]")
# dfs_episodes_new_flat.index.name = 'episodestart_timestamp'
dfs_episodes_new_flat.index
dfs_episodes_new_flat.dtypes
# dfs_episodes_new_flat.columns.name = 'episodestart_timestamp'
dfs_episodes_new_flat.columns
dfs_episodes_new_flat

In [ ]:
try:
    ddf_episodes_new = dd.from_pandas(dfs_episodes_new_flat, npartitions=1)
except Exception as e:
    print(e)
ddf_episodes_new.dtypes
# dfs_episodes_new_flat

In [ ]:
os.getcwd()
custom_metadata = {
    b"eos": b'{"length":[6, 600, 5],"timezeone":"sh","units":["kph","pct","pct"],"data_propensity":[50, 1, 4],"Dataset Description": "MP vehicle from TBox"}'
}

try:
    with ProgressBar():
        ddf_episodes_new.to_parquet(
            "eos_complete_episodes",
            engine="pyarrow",
            compression="snappy",
            partition_on=["vehicle__", "driver__", "episodestart__"],
            write_metadata_file=True,
            custom_metadata=custom_metadata,
        )
except Exception as e:
    print(e)

In [ ]:
ddf = dd.read_parquet(
    "eos_complete_episodes",
    engine="pyarrow",
    compression="snappy",
    ignore_metadata_file=False,
    infer_divisions=True,
)
pq_meta = pq.read_metadata("eos_episodes/_common_metadata")
custom_meta_info = pq_meta.metadata[b"eos"]
custom_meta_info = json.loads(custom_meta_info)
for key, val in custom_meta_info.items():
    print(f"{key}: {val}")
ddf.dtypes
df = ddf.compute()

# decoding columns index
multi_tpl = [tuple(col.split("_")) for col in df.columns]
multi_col = pd.MultiIndex.from_tuples(multi_tpl)
i1 = multi_col.get_level_values(0)
i1 = ["" if str(idx) in (str(pd.NA), "nan", "") else idx for idx in i1]
i2 = multi_col.get_level_values(
    1
)  # must be null string instead of the default pd.NA or np.nan
i2 = [
    "" if str(idx) in (str(pd.NA), "nan", "") else idx for idx in i2
]  # convert index of level 2 type to int and '' if NA
i3 = multi_col.get_level_values(
    2
)  # must be null string instead of the default pd.NA or np.nan
i3 = [
    "" if str(idx) in (str(pd.NA), "nan", "") else int(idx) for idx in i3
]  # convert index of level 2 type to int and '' if NA


multi_col = pd.MultiIndex.from_arrays([i1, i2, i3])
multi_col.names = ["tuple", "rows", "idx"]
multi_col

# # decoding index
# multi_tuple = [tuple(idx.split('_')) for idx in df.index]
# multi_idx = pd.MultiIndex.from_tuples(multi_tuple)

# i0 = multi_idx.get_level_values(
#     0
# )  # must be null string instead of the default pd.NA or np.nan
# i0 = [
#     ''
#     if str(idx) in (str(pd.NA), 'nan', '')
#     else datetime.strptime(idx, '%Y-%m-%dT%H:%M:%S.%f')
#     for idx in i0
# ]  # convert index of level 2 type to int and '' if NA
# i1 = multi_idx.get_level_values(
#     1
# )  # must be null string instead of the default pd.NA or np.nan
# i1 = [
#     ''
#     if str(idx) in (str(pd.NA), 'nan', '')
#     else datetime.strptime(idx, '%Y-%m-%dT%H:%M:%S.%f')
#     for idx in i1
# ]  # convert index of level 2 type to int and '' if NA
# df_episodes_read_multiidx = df_episodes_read.copy()
# multi_idx = pd.MultiIndex.from_arrays([i0, i1], names=('episodestart', 'timestamp'))
#
# multi_idx.names = ['episodestart', 'timestamp']

df.columns = multi_col
# df.index = multi_idx

df = df.set_index(["vehicle", "driver", "episodestart", df.index])
df.index.dtypes
df.index
# len(multi_idx)

### add rows to a partition

In [ ]:
ddf = dd.read_parquet(
    "eos_complete_episodes",
    engine="pyarrow",
    compression="snappy",
    ignore_metadata_file=False,
    infer_divisions=True,
)
ddf.index
ddf.npartitions
ddf.divisions
ddf.dtypes

# ddf['episodestart'] = ddf['episodestart'].astype('datetime64[ns]')  # error,  not allowed for dask dataframe
# ddf.assign(episodestart=ddf['episodestart'].astype('datetime64[ns]'))
ddf = ddf["episodestart"].astype("datetime64[ns]")
ddf.dtypes
# ddf.compute()

In [ ]:
dfs_episode5 = dfs_episode4.copy()
dfs_episode5.index = dfs_episode4.index.set_levels(
    [episodestart - pd.Timedelta(9, "d")], level="episodestart"
)
dfs_episode5.index = dfs_episode4.index.set_levels(
    [[trucks_by_id["MP74"].vid], [drivers_by_id["zheng-longfei"].pid]],
    level=["vehicle", "driver"],
    verify_integrity=False,
)
# dfs_episode5 = dfs_episode5.swaplevel(0,1, axis=0).swaplevel(1,2,axis=0)
dfs_episode5 = dfs_episode5.reset_index(level=["vehicle", "driver", "episodestart"])

dfs_episode5["vehicle"] = dfs_episode5["vehicle"].astype("category")
dfs_episode5["driver"] = dfs_episode5["driver"].astype("category")
# dfs_episode5['episodestart'] = dfs_episode5['episodestart'].astype('category')
dfs_episode5.dtypes


# encoding columns index
dfs_episode5.columns = [
    f"{x[0]}_{x[1]}_{x[2]}"
    if (x[1] != "" and x[2] != "")
    else f"{x[0]}_{x[1]}_"
    if (x[1] != "" and x[2] == "")
    else f"{x[0]}__{x[2]}"  # !!! dunder!!!
    if (x[2] != "")
    else f"{x[0]}__"
    for x in dfs_episode5.columns.to_flat_index()
]
# df_episode_new.index = [
#     f'{x[0].strftime("%Y-%m-%dT%H:%M:%S.%f")}_{x[1].strftime("%Y-%m-%dT%H:%M:%S.%f")}'
#     if x[1] != ''
#     else f'{x[0].strftime("%Y-%m-%dT%H:%M:%S.%f")}'
#     for x in dfs_episode5.index.to_flat_index()
# ]
# df_episode_new.dtypes
dfs_episode5

In [ ]:
dfs_episode6 = dfs_episode4.copy()
dfs_episode6.index = dfs_episode4.index.set_levels(
    [episodestart - pd.Timedelta(19, "d")], level="episodestart"
)
dfs_episode6.index = dfs_episode4.index.set_levels(
    [[trucks_by_id["MP73"].vid], [drivers_by_id["wang-cheng"].pid]],
    level=["vehicle", "driver"],
    verify_integrity=False,
)
# dfs_episode6 = dfs_episode5.swaplevel(0, 1, axis=0).swaplevel(1, 2, axis=0)
dfs_episode6 = dfs_episode6.reset_index(level=["vehicle", "driver", "episodestart"])

dfs_episode6["vehicle"] = dfs_episode6["vehicle"].astype("category")
dfs_episode6["driver"] = dfs_episode6["driver"].astype("category")
# dfs_episode6['episodestart'] = dfs_episode6['episodestart'].astype('category')
dfs_episode6.dtypes
# encoding columns index
dfs_episode6.columns = [
    f"{x[0]}_{x[1]}_{x[2]}"
    if (x[1] != "" and x[2] != "")
    else f"{x[0]}_{x[1]}_"
    if (x[1] != "" and x[2] == "")
    else f"{x[0]}__{x[2]}"  # !!! dunder!!!
    if (x[2] != "")
    else f"{x[0]}__"
    for x in dfs_episode6.columns.to_flat_index()
]
# dfs_episode6.index = [
#     f'{x[0].strftime("%Y-%m-%dT%H:%M:%S.%f")}_{x[1].strftime("%Y-%m-%dT%H:%M:%S.%f")}'
#     if x[1] != ''
#     else f'{x[0].strftime("%Y-%m-%dT%H:%M:%S.%f")}'
#     for x in dfs_episode6.index.to_flat_index()
# ]
# df_episode_new.dtypes
dfs_episode6

#### encoding single dataframe of multiindex into dask single index dataframe

In [ ]:
ddf_read = dd.read_parquet(
    "eos_complete_episodes",
    engine="pyarrow",
    compression="snappy",
    ignore_metadata_file=False,
    infer_divisions=True,
)
# df_all = ddf_read.compute()
# df_all
# idx = pd.IndexSlice
# col_epistart = ddf_read.loc[:, 'episodestart__'].astype('datetime64[ns]').compute()
# col_epistart
#
# ddf_read.loc[:, 'episodestart__'] = ddf_read.loc[:, 'episodestart__'].astype(
#     'datetime64[ns]'
# )
ddf_read["episodestart__"] = ddf_read["episodestart__"].astype("datetime64[ns]")
ddf_read.compute()

In [ ]:
# ddf_episodes_new = dd.concat([dfs_episode5, dfs_episode6])
# ddf_combine = dd.concat([ddf_read, ddf_episodes_new])
ddf_combine = dd.concat([ddf_read, dfs_episode5, dfs_episode6])
ddf_combine.compute()
ddf_combine.dtypes

In [ ]:
# ddf_list = []
# for n in range(ddf_read.npartitions):
#     ddf_list.append(ddf_read.partitions[n])
#     # ddf_list[n].compute()
# len(ddf_list)
# type(ddf_list[0])

In [ ]:
# df_new_list = [dfs_episode5, dfs_episode6]
# df_attach = []
# for df in df_new_list:
#     bHit = False
#     for i, ddf in enumerate(ddf_list):
#         # if dfs_episode_new['vehicle']
#         print(f"{i}")
#         # df = ddf.compute()
#         # ddf.columns
#         # ddf.dtypes
#         # type(ddf)
#         vehicle = ddf['vehicle__'].compute()[0]
#         driver = ddf['driver__'].compute()[0]
#         # df_episode_new = df_episode_new.append(ddf)
#         if df['vehicle__'][0] == vehicle and df['driver__'][0] == driver:
#             bHit = True
#             print(
#                 f'hit {i}{"st" if i==1 else "nd" if i==2 else "rd" if i==3 else "th"} partition'
#             )
#             # ddf_list[i] = dd.concat([ddf, df], axis=0)
#             df_attach.append(df)
#             # append ddf to dfs_episode_new
#
#     if bHit == False:
#         print('no hit')
#         df_attach.append(df)
#         # append ddf to dfs_episode_new
#
#
# #     c_ep = df_episode_new['ep
#     dfs_episode_new = dfs_episode_newappend(ddf)
# print(f"splicing dfs_episode_new {c_ep} with
# df_attach.append(df)

In [ ]:
# df_attach[0].dtypes

In [ ]:
# ddf_list.append(df_attach[0])
# ddf_list[0].dtypes
# ddf_all = dd.concat(ddf_list, axis=0, join='outer')

In [ ]:
# ddf_all.compute()os.getcwd()
custom_metadata = {
    b"eos": b'{"length":[8, 800, 8],"timezeone":"sh","units":["kph","pct","pct"],"data_propensity":[50, 1, 4],"Dataset Description": "MP vehicle from TBox"}'
}

try:
    with ProgressBar():
        ddf_combine.to_parquet(
            "eos_combine_episodes",
            engine="pyarrow",
            compression="snappy",
            partition_on=["vehicle__", "driver__", "episodestart__"],
            write_metadata_file=True,
            custom_metadata=custom_metadata,
        )
except Exception as e:
    print(e)

In [ ]:
# ddf_all.compute()
ddf = dd.read_parquet(
    "eos_combine_episodes",
    engine="pyarrow",
    compression="snappy",
    ignore_metadata_file=False,
    infer_divisions=True,
)
pq_meta = pq.read_metadata("eos_combine_episodes/_common_metadata")
# print(table_meta)
# print(table_meta.metadata[b'eos'])
custom_meta_info = pq_meta.metadata[b"eos"]
custom_meta_info = json.loads(custom_meta_info)
# custom_meta_info

for key, val in custom_meta_info.items():
    print(f"{key}: {val}")

df = ddf.compute()

multi_tpl = [tuple(col.split("_")) for col in ddf.columns]
multi_col = pd.MultiIndex.from_tuples(multi_tpl)
i1 = multi_col.get_level_values(0)
i1 = [
    "" if str(idx) in (str(pd.NA), "nan", "") else idx for idx in i1
]  # convert index of level 2 type to int and '' if NA
i2 = multi_col.get_level_values(
    1
)  # must be null string instead of the default pd.NA or np.nan
i2 = [
    "" if str(idx) in (str(pd.NA), "nan", "") else idx for idx in i2
]  # convert index of level 2 type to int and '' if NA
i3 = multi_col.get_level_values(
    2
)  # must be null string instead of the default pd.NA or np.nan
i3 = [
    "" if str(idx) in (str(pd.NA), "nan", "") else int(idx) for idx in i3
]  # convert index of level 2 type to int and '' if NA

multi_col = pd.MultiIndex.from_arrays([i1, i2, i3])
multi_col.names = ["tuple", "rows", "idx"]
df.columns = multi_col

# multi_idx = [tuple(idx.split('_')) for idx in ddf.index]
# multi_idx = pd.MultiIndex.from_tuples(multi_idx)
# i0 = multi_idx.get_level_values(
#     0
# )  # must be null string instead of the default pd.NA or np.nan
# i0 = [
#     ''
#     if str(idx) in (str(pd.NA), 'nan', '')
#     else datetime.strptime(idx, '%Y-%m-%dT%H:%M:%S.%f')
#     for idx in i0
# ]  # convert index of level 2 type to int and '' if NA
# i1 = multi_idx.get_level_values(
#     1
# )  # must be null string instead of the default pd.NA or np.nan
# i1 = [
#     ''
#     if str(idx) in (str(pd.NA), 'nan', '')
#     else datetime.strptime(idx, '%Y-%m-%dT%H:%M:%S.%f')
#     for idx in i1
# ]  # convert index of level 2 type to int and '' if NA
# multi_idx = pd.MultiIndex.from_arrays([i0, i1], names=('episodestart', 'timestamp'))
# df.index = multi_idx


df = df.set_index(["vehicle", "driver", "episodestart", df.index])
df
df.columns
df.index
# len(multi_idx)

## Sample Quadratuple from parquet files

In [ ]:
ddf = dd.read_parquet(
    "eos_combine_episodes",
    engine="pyarrow",
    compression="snappy",
    ignore_metadata_file=False,
    infer_divisions=True,
)
df = ddf.compute()
df = df.sort_index()
df

In [ ]:
ddf_list = []
for n in range(ddf.npartitions):
    ddf_list.append(ddf.partitions[n])
len(ddf_list)
type(ddf_list[0])

## Sample Quadratuple from parquet files


In [ ]:
target_vehicle = "VB7"
target_driver = "wang-cheng"
partition = []
for i, ddf in enumerate(ddf_list):
    # if dfs_episode_new['vehicle']
    print(f"{i}")
    # df = ddf.compute()
    # ddf.columns
    # ddf.dtypes
    vehicle = ddf["vehicle__"].compute()[0]
    driver = ddf["driver__"].compute()[0]
    # df_episode_new = df_episode_new.append(ddf)
    if target_vehicle == vehicle and target_driver == driver:
        bHit = True
        print(
            f'hit {i}{"st" if i==1 else "nd" if i==2 else "rd" if i==3 else "th"} partition'
        )
        # k = i
        partition.append(i)

        # ddf_list[i] = dd.concat([ddf, df], axis=0)
        # append ddf to dfs_episode_new

if bHit == False:
    print("no hit")
    # ddf_list.append(df_episode_new)
    # append ddf to dfs_episode_new

partition
ddf_target = dd.concat([ddf_list[i] for i in partition], axis=0)
# ddf_target
# # ddf_target.head()
df_target = ddf_target.compute()
df_target
# # df_target

# #     c_ep = df_episode_new['ep
# #     dfs_episode_new = dfs_episode_newappend(ddf)
# # print(f"splicing dfs_episode_new {c_ep} with

In [ ]:
tuple_sample = ddf_target.sample(frac=0.2).compute()
tuple_sample["episodestart__"]

In [ ]:
ddf_target.sample(frac=0.2).compute()